# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Category:
            class: AppBundle\Entity\typeDeSignalement
            label: 'typeDeSignalement'
            list:
                title: 'Product %%entity_label%%'
                actions:
                    - { name: 'Voir', label: 'Voir', icon: 'search' }
                    - { name: 'Editer', label: 'Editer', icon: 'edit' }
                    - { name: 'Supprimer', label: 'Supprimer', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'libelle', label: 'Libelle' }
                    - 'products'
            show:
                fields:
                    - 'id'
                    - { property: 'libelle', label: 'Libelle' }
                    - 'products'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'libelle', label: 'Libelle', css_class: 'large', help: 'As displayed on the website (the slug is auto-generated)' }
                    # if you want to add products when creating categories, add the 'by_reference' option
                    # - { property: 'products', type_options: { by_reference: false } }